name: Dependency Audit
on:
  schedule:
    # Run every Monday at 00:00 UTC
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  dependency-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        id: audit
        run: |
          npm audit --json > audit-results.json || true

      - name: Check for critical vulnerabilities
        if: always()
        run: |
          if [ -f audit-results.json ]; then
            CRITICAL_COUNT=$(jq '.metadata.vulnerabilities.critical // 0' audit-results.json)
            if [ "$CRITICAL_COUNT" -gt 0 ]; then
              echo "CRITICAL_VULNERABILITIES=$CRITICAL_COUNT" >> $GITHUB_ENV
              exit 1
            fi
          fi

      - name: Notify maintainers
        if: failure() && steps.audit.outcome == 'failure'
        uses: actions/github-script@v7
        with:
          script: |
            const { data } = await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `⚠️ **Dependency Audit Failed** ⚠️\n` +
                    `Critical vulnerabilities detected: ${{ env.CRITICAL_VULNERABILITIES }}\n` +
                    `[View full report](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})`
            })
